### ISSUE TITLE
there is erroe when i run the script "udnet_denoise_demo.m"

### ISSUE THREAD

**Issue by chensongkui** [cig-skoltech/UDNet#2]
Hi, Mr. Stamatis Lefkimmiatis, when i run the script "udnet_denoise_demo.m", there is error, the error information is follow:
![图片](https://user-images.githubusercontent.com/15098181/54109163-d2ea8700-4418-11e9-8caa-687bd6925d24.png)
Error using vl_setupnn (line 36)
unsupported OS

Error in run (line 91)
evalin('caller', strcat(script, ';'));

Error in udnet_denoise_demo (line 3)
run(fullfile(fileparts(mfilename('fullpath')), ...

can you tell me how to solve this problem? thank you very much.

**Comment by arscarrot** [comment]
> Hi, Mr. Stamatis Lefkimmiatis, when i run the script "udnet_denoise_demo.m", there is error, the error information is follow:
> ![图片](https://user-images.githubusercontent.com/15098181/54109163-d2ea8700-4418-11e9-8caa-687bd6925d24.png)
> Error using vl_setupnn (line 36)
> unsupported OS
> 
> Error in run (line 91)
> evalin('caller', strcat(script, ';'));
> 
> Error in udnet_denoise_demo (line 3)
> run(fullfile(fileparts(mfilename('fullpath')), ...
> 
> can you tell me how to solve this problem? thank you very much.

I have the same problem,.

**Comment by stamatisl80** [comment]
Hi, from the error that you report it seems that you are trying to run the code on a different Operating system than Mac OS or Linux. The provided code supports only these two operating systems
